export const LOADING_START = 'EVENT/LOADING_START';
export const LOADING_END = 'EVENT/LOADING_END';

export const SHOW_NEW_EVENT_FORM = 'EVENT/SHOW_NEW_EVENT_FORM';

export const SET_NEW_EVENT = 'EVENT/SET_NEW_EVENT';

export const ADD_EVENT = 'EVENT/ADD_EVENT';
export const ADD_EVENT_SUCCESS = 'EVENT/ADD_EVENT_SUCCESS';
export const ADD_EVENT_ERROR = 'EVENT/ADD_EVENT_ERROR';

export const GET_EVENTS = 'EVENT/GET_EVENTS';
export const GET_EVENTS_SUCCESS = 'EVENT/GET_EVENTS_SUCCESS';
export const GET_EVENTS_ERROR = 'EVENT/GET_EVENTS_ERROR';
